### PR TITLE
Fixes #6 Better exception when MikTex is not installed

### LINKED ISSUE #6: Better exception when MikTex is not installed
Right now we get a crash
Application:
PK-Sim® 7.1.0 - Build 66

One or more errors occurred.
-----------------------------------------------------
Value cannot be null.
Parameter name: path1

Stack trace:
```
at System.IO.Path.Combine(String path1, String path2, String path3)
   at OSPSuite.TeXReporting.TeX.CompilerConfiguration.get_MikTexExecutablePath()
   at OSPSuite.TeXReporting.TeX.CompilerConfiguration.get_Texify()
   at OSPSuite.TeXReporting.TeX.TeXCompiler.<CompileTex>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OSPSuite.TeXReporting.ReportCompiler.<CompileReport>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.TeXReporting.ReportCreator.<ReportToPDF>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.Infrastructure.Reporting.ReportingTask.<CreateReportAsync>d__6.MoveNext()
 --- End of inner exception stack trace ---
```

### PR DESCRIPTION
**Pull request by msevestre**

### CODE REVIEW

File: src/OSPSuite.TeXReporting/TeX/CompilerConfiguration.cs [hunk 1]
```diff
@@ -62,7 +53,11 @@ public static string MikTEXPortablePath
                if (!string.IsNullOrEmpty(path))
                   return path;
 
-               return Environment.GetEnvironmentVariable(MIK_TEX_INSTALL_DIR);
+               path = Environment.GetEnvironmentVariable(MIK_TEX_INSTALL_DIR);
+               if (!string.IsNullOrEmpty(path))
+                  return path;
+
+               throw new MikTexInstallationException();
```
Comment (msevestre) [inline src/OSPSuite.TeXReporting/TeX/CompilerConfiguration.cs:60]: need to throw here if not found!
